"""add department and graduation_year to placement_profiles

Revision ID: 252cdf63be65
Revises: d2d8f60d2a42
Create Date: 2026-08-26 02:17:07.889734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252cdf63be65'
down_revision: Union[str, Sequence[str], None] = 'd2d8f60d2a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placement_profiles', sa.Column('department', sa.String(), nullable=True))
    op.add_column('placement_profiles', sa.Column('graduation_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('placement_profiles', 'graduation_year')
    op.drop_column('placement_profiles', 'department')
    # ### end Alembic commands ###
