"""create placement_profiles table

Revision ID: 6a11ed0e3480
Revises: 
Create Date: 2026-08-21 11:00:06.133908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a11ed0e3480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('preferred_role', sa.String(), nullable=True),
    sa.Column('preferred_location', sa.String(), nullable=True),
    sa.Column('preferred_industry', sa.String(), nullable=True),
    sa.Column('work_preference', sa.String(), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('has_active_backlog', sa.Boolean(), nullable=True),
    sa.Column('cgpa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leetcode_url', sa.String(), nullable=True),
    sa.Column('codechef_url', sa.String(), nullable=True),
    sa.Column('hackerrank_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_profiles')
    # ### end Alembic commands ###
