"""add file upload fields to resumes

Revision ID: 9e5560f82467
Revises: 174bb11666c1
Create Date: 2026-08-29 02:00:26.904126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5560f82467'
down_revision: Union[str, Sequence[str], None] = '174bb11666c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'original_filename')
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###
