"""create placement_stories table

Revision ID: a21deb384417
Revises: e1329215787c
Create Date: 2026-08-26 15:20:16.177548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a21deb384417'
down_revision: Union[str, Sequence[str], None] = 'e1329215787c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('preparation_duration', sa.String(), nullable=True),
    sa.Column('topics_prepared', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('resources_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interview_experience_text', sa.Text(), nullable=True),
    sa.Column('advice_for_juniors', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['placement_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_stories')
    # ### end Alembic commands ###
